---
resources:


  - name: source-base-code
    type: git
    icon: github-circle
    source:
      uri: ((code-base-repo))
      branch: master

  - name: docker-hub
    type: docker-image
    source:
      repository: ((hub-username))/tenant-details
      username: ((hub-username))
      password: ((hub-password))
  
  - name: cd-config
    type: git
    source:
      uri: ((cd-config-repo))
      branch: master
      username: ((github-username))
      password: ((github-password))

  - name: kube-resources
    type: git
    source:
      uri: ((kube-resources-repo))
      branch: master
      username: ((github-username))
      password: ((github-password))


jobs:

  # - name: get-dependencies
  #   public: true
  #   serial: true
  #   plan:
  #     - get: source-base-code
  #       trigger: true
  #     - task: install-deps
  #       config:
  #         platform: linux
  #         image_resource:
  #           type: docker-image
  #           source: 
  #             repository: node
  #             tag: 13.14-slim
  #         inputs:
  #           - name: source-base-code
  #         run:
  #           path: /bin/sh
  #           args:
  #             - -c
  #             - |
  #               echo "Node version: $(node --version)"
  #               echo "NPM version: $(npm --version)"
  #               cd source-base-code
  #               npm install

  - name: build-docker-image
    plan:
      - get: source-base-code
        trigger: true
      - put: docker-hub
        params:
          # The directory containing the Dockerfile
          build: source-base-code
          tag_file: source-base-code/.git/ref
  


  - name: update-deployment-files
    public: true
    serial: true
    plan:
    - get: source-base-code
      passed:
      - build-docker-image
      trigger: true
    - get: cd-config
      trigger: true
    - get: kube-resources
    - task: replace-deployment-image
      file: cd-config/tasks/replacement-task.yml
    - task: create-resource-commit
      file: cd-config/tasks/create-commit.yml
    - put: kube-resources
      params:
        repository: kube-resources

  # - name: bump-deployments
  #   public: true
  #   plan:
  #   - get: cd-config
  #     passed:
  #     - update-deployment-files
  #     trigger: true
  #   - get: kube-resources
  #   - task: create-resource-commit
  #     # file: cd-config/tasks/create-commit.yml
  #     config:
  #       platform: linux
  #       image_resource:
  #         type: docker-image
  #         source:
  #           repository: alpine/git
  #       inputs:
  #         - name: cd-config
  #         - name: kube-resources

  #       outputs:
  #       - name: kube-resources

  #       run:
  #         path: sh
  #         args:
  #         - -exc
  #         - |
  #           ls -la
  #           ls -la cd-config
  #           chmod +x cd-config/scripts/
  #           ls -la cd-config/scripts
  #           sh cd-config/scripts/create-commit.sh
  #   - put: kube-resources
  #     params:
  #       repository: kube-resources 
