---
resources:


  - name: source-base-code
    type: git
    icon: microsoft-github
    source:
      uri: ((code-base-repo))
      branch: master

  - name: docker-hub
    type: docker-image
    source:
      repository: ((hub-username))/tenant-details
      username: ((hub-username))
      password: ((hub-password))
  
  - name: cd-resources
    type: git
    source:
      uri: ((cd-resources-repo))
      branch: master
      username: ((github-username))
      password: ((github-password))

  - name: kube-resources
    type: git
    source:
      uri: ((kube-resources-repo))
      branch: master
      username: ((github-username))
      password: ((github-password))


jobs:

  # - name: get-dependencies
  #   public: true
  #   serial: true
  #   plan:
  #     - get: source-base-code
  #       trigger: true
  #     - task: install-deps
  #       config:
  #         platform: linux
  #         image_resource:
  #           type: docker-image
  #           source: 
  #             repository: node
  #             tag: 13.14-slim
  #         inputs:
  #           - name: source-base-code
  #         run:
  #           path: /bin/sh
  #           args:
  #             - -c
  #             - |
  #               echo "Node version: $(node --version)"
  #               echo "NPM version: $(npm --version)"
  #               cd source-base-code
  #               npm install

  - name: build-docker-image
    plan:
      - get: source-base-code
        trigger: true
      - put: docker-hub
        params:
          # The directory containing the Dockerfile
          build: source-base-code
          tag_file: source-base-code/.git/ref
  


  - name: update-deployment
    public: true
    serial: true
    plan:      
    - get: source-base-code
    - get: cd-resources
      trigger: true
    - get: kube-resources
    - task: replace-deployment-image
      file: cd-resources/tasks/replacement-task.yml
      vars:
        imageVersion: source-base-code/.git/ref
    - task: create-resource-commit
      # file: cd-resources/tasks/create-commit.yml
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine/git

        inputs:
          - name: target-resources
          - name: cd-resources
          - name: kube-resources

        outputs:
        - name: kube-resources

        run:
          path: sh
          args:
          - -exc
          - |
            chmod +x cd-resources/scripts/
            ls -la cd-resources/scripts
            sh cd-resources/scripts/create-commit.sh

    - put: kube-resources
      params:
        repository: kube-resources

