---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine/git

inputs:
  - name: transition-resources
  - name: cd-config
  - name: kube-resources

outputs:
- name: kube-resources

params:
  TENANT: ((tenant-name))

run:
  path: sh
  args:
  - -exc
  - |
    #chmod +x cd-config/scripts/
    sh cd-config/scripts/create-commit.sh