---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine/git

inputs:
  - name: transition-resources
  - name: cd-resources
  - name: kube-resources

outputs:
- name: kube-resources

run:
  path: sh
  args:
  - -exc
  - |
    ls -la cd-resources
    chmod +x cd-resources/scripts/
    ls -la cd-resources/scripts
    sh cd-resources/scripts/create-commit.sh