---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine/git

inputs:
  - name: target-resources
  - name: cd-resources

outputs:
- name: cd-resources

run:
  path: sh
  args:
  - cd-resources/scripts/create-commit.sh