---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: mikefarah/yq

inputs:
  - name: source-base-code
  - name: cd-config

outputs:
- name: transition-resources

run:
  path: sh 
  args:
  - cd-config/scripts/replacement-task.sh
  - source-base-code/test.yaml
  - karankapoor/tenant-details
